server:
  port: 8075
  servlet:
    context-path: /irisicm

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/irisicm?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      #设置单个文件的大小
      max-file-size: 50MB
      #设置总上传的数据大小
      max-request-size: 1024MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: cn.irisicm.entity
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

# 日志
logging:
  config: classpath:logback-spring.xml
